#!/bin/bash
#
#
#	 Copyright @ DestructHub Authors
#
#

# usage: add <problem-num> <answer>

if [ -x "$(command -v md5)" ]; then
    alias md5sum='xargs md5 -s'
elif [ ! -x "$(command -v md5sum)" ]; then
    echo "None of 'md5' and 'md5sum' cmd line are not found"
    echo "Try install coretuils before using this script"
    exit 1
fi

num=$(expr $1 + 0)
dir="Problem"$(printf "%03d" $num)
readme="[The original source of problem](https://projecteuler.net/problem=$num)"
hash=$(printf $2 | md5sum)
mkdir -p $dir
echo "Created folder $dir."
echo $hash > $dir/.hash
echo "$dir/.hash => $hash"
echo $readme > $dir/README.md
echo "Created file $dir/README.md"
echo "Added solution template for problem $num of ProjectEuler"
