#!/bin/bash

#git fetch origin

function diff_files () {
    git diff origin/master --name-only
}

function search () {
    git diff origin/master --name-only | xargs python3 stats.py --build --files
}

cmd="$1"

if [ "$cmd" = "--staged-only" ] || [ "$cmd" = "-so" ]; then
    search
fi

exit 1
