#!/bin/bash

#git fetch origin

function diff_files () {
    git diff origin/master --name-only
}

function search () {
    git diff origin/master --name-only | python3 stats.py --search
}

cmd="$1"

if [ "$cmd" = "--staged-only" ] || [ "$cmd" = "-so" ]; then
    search
fi

exit 1
