CXX = g++
LFLAGS = -lm -Wall -std=c++0x -o
TARGET =  solution_01
EXTENSION_TARGET = cpp
EXTENSION_OUT = out


all:
	$(CXX) $(LFLAGS) $(TARGET).$(EXTENSION_OUT) $(TARGET).$(EXTENSION_TARGET)
clean:
	rm -v *.$(EXTENSION_OUT)
run:
	./$(TARGET).$(EXTENSION_OUT)