CXX = g++
LFLAGS = -lm -Wall -std=c++11 -o
TARGET =  solution_1
EXTENSION_TARGET = cpp
EXTENSION_OUT = out


all: 
	$(CXX) $(LFLAGS) $(TARGET).$(EXTENSION_OUT) $(TARGET).$(EXTENSION_TARGET)
clean: 
	rm -v *.$(EXTENSION_OUT)
run:
	./$(TARGET).$(EXTENSION_OUT)
