/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

#include <stdio.h>
#include <stdlib.h>

#define INT sizeof(int)

typedef struct fib {
  int *sequence;
  int length;
} _fib;

int even(int);
_fib fibonacci(int);

int main(void) {
  _fib numbers;
  int i, sum_even;

  numbers = fibonacci(4000000);

  sum_even = 0;
  for (i = 0; i < numbers.length; i++) {
    if (even(numbers.sequence[i]))
      sum_even += numbers.sequence[i];
  }

  printf ("%d", sum_even);

  return 0;
}

int even(int value) {
  return !(value & 1);
}

_fib fibonacci(int limit) {
  _fib numbers;
  int a, b;

  numbers.sequence = NULL;
  numbers.length = 0;
  a = 0;
  b = 1;

  while ((a+b) < limit) {
    numbers.sequence = (int *) realloc (numbers.sequence, ++numbers.length * INT);
    numbers.sequence[numbers.length-1] = a+b;

    a = b;
    b = numbers.sequence[numbers.length-1];
  }

  return numbers;
}