# Highly divisible triangular number
# Problem 12

# The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

# 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

# Let us list the factors of the first seven triangle numbers:

#      1: 1
#      3: 1,3
#      6: 1,2,3,6
#     10: 1,2,5,10
#     15: 1,3,5,15
#     21: 1,3,7,21
#     28: 1,2,4,7,14,28

# We can see that 28 is the first triangle number to have over five divisors.

# What is the value of the first triangle number to have over five hundred divisors?
from itertools import combinations

def trianglenums():
    n = 1
    while True:
        yield n*(n+1)/2
        n += 1
def factoring(n):
    divs = [1]
    i = 2
    #fatorando
    while n > 1:
        while(n % i == 0):
            n /= i
            divs.append(i)
        i+= 1
    return divs
def divisors(n):
    divs = factoring(n)
    primes = divs[1:]
    
    for j in range(1, len(primes)):
        for comb in combinations(primes, j + 1):
            newdiv = reduce(lambda x, y: x*y, comb)
            if newdiv <= n and newdiv not in divs:
                divs.append(newdiv)
    return len(divs)
#resuming all (one line! D:) FDP! (divisors + factoring function). The perfomance it's the same
def factors(n):    
    return set(reduce(list.__add__, ([i, n//i] for i in range(1, int(n**0.5) + 1) if n % i == 0))) 


for i in trianglenums():
    if divisors(i) > 500:
        print('Answer: %d' %i)
        quit()
