CXX = gcc
LFLAGS = -O3 -lm -Wall -o
TARGET =  solution_1
EXTENSION_TARGET = c
EXTENSION_OUT = out


all: 
	$(CXX) $(TARGET).$(EXTENSION_TARGET) $(LFLAGS) $(TARGET).$(EXTENSION_OUT)
clean: 
	rm -v *.$(EXTENSION_OUT)
run:
	./$(TARGET).$(EXTENSION_OUT)
