CXX = gcc
LFLAGS = -lm -Wall -o
TARGET =  solution_1
EXTENSION_TARGET = c
EXTENSION_OUT = out


all:
	$(CXX) $(LFLAGS) $(TARGET).$(EXTENSION_OUT) $(TARGET).$(EXTENSION_TARGET)
clean:
	rm -v *.$(EXTENSION_OUT)
run:
	./$(TARGET).$(EXTENSION_OUT)
